runtime: python39

instance_class: F2

entrypoint: gunicorn -b :$PORT main:app

env_variables:
  ENV_VAR_NAME: "env_var_value"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

runtime_config:
  python_version: 3.9